### ISSUE TITLE
Show how long ago rather than date/timestamps

### ISSUE THREAD

**Issue by BoyCook** [BoyCook/LifeStreamTW5#1]
Add widget to get the difference from 'now' to specific date and then display in the appropriate unit.

**Comment by Jermolene** [comment]
Before the recent big refactoring I had a view widget with the same functionality, but adding dynamic updates in the browser. Have a look at this:

https://github.com/Jermolene/TiddlyWiki5/blob/cf15b128c16f45a5f0139a91ce21107c6dccf2a8/core/modules/macros/view/viewers/relativedate.js

It needs updating to slot into the new render mechanism.

**Comment by BoyCook** [comment]
I actually already did this with the datediff.js module:

https://github.com/BoyCook/CraigCook/blob/master/editions/lifestream/tiddlers/modules/widgets/datediff.js

**Comment by Jermolene** [comment]
Yes, the difference is that the custom format viewer implementation also dynamically updates the DOM on a timer, so that the relative time is updated in real time.

**Comment by BoyCook** [comment]
Ah ok that sounds better. I'll take a look.
